trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  configuration: 'Release'
  runtimeId: 'linux-x64'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6 SDK'
  inputs:
    packageType: 'sdk'
    version: 6.0.x

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    arguments: '--configuration $(configuration)'
    projects: 'Estimmo.Test/Estimmo.Test.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    projects: 'Estimmo.Api/Estimmo.Api.csproj'
    publishWebProjects: true
    arguments: '--configuration $(configuration) --runtime $(runtimeId) --no-self-contained --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: "Upload Artifacts"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'estimmo-api' 
