version: "3.1"
services:
  postgres:
    image: postgis/postgis:latest
    shm_size: 2g
    container_name: estimmo-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "8082:5432"
    environment:
      - POSTGRES_USER=estimmo
      - POSTGRES_PASSWORD=estimmo
      - POSTGRES_DB=estimmo

volumes:
  db-data:
    driver: local
